# Generated by Django 5.1.2 on 2025-02-02 11:39

import django.contrib.auth.validators
import tracker.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcechannel',
            name='source_link',
            field=models.URLField(max_length=128, validators=[tracker.validators.validate_url]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AddConstraint(
            model_name='sourcechannel',
            constraint=models.UniqueConstraint(fields=('user', 'source_link'), name='unique_source_link'),
        ),
    ]
